```bash
#!/bin/bash
# Quick Git Reference Script for Infrix Internship

echo "🚀 INFRIX GIT QUICK REFERENCE"
echo "=============================="
echo ""
echo "🔄 BASIC WORKFLOW:"
echo "  1. git status          # Check what changed"
echo "  2. git add .           # Stage all changes"
echo "  3. git commit -m 'msg' # Save changes"
echo "  4. git push            # Upload to GitHub"
echo ""
echo "📅 VIEW HISTORY:"
echo "  git log --oneline --graph  # See pretty history"
echo "  git diff                   # See what changed"
echo ""
echo "🌿 BRANCHES:"
echo "  git branch                 # List branches"
echo "  git checkout -b feature    # Create & switch to branch"
echo "  git merge feature          # Merge branch"
echo ""
echo "⏪ UNDO THINGS:"
echo "  git checkout -- file       # Discard changes"
echo "  git reset HEAD file        # Unstage file"
echo "  git reset --soft HEAD~1    # Undo last commit (keep changes)"
echo ""
echo "💡 TIP: Always run 'git status' before anything else!"
echo ""
echo "✅ Practice these commands today!"